version: '3'
services:
  postgres:
    image: supabase/postgres:15.1.0.23
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  supabase-studio:
    image: supabase/studio:latest
    restart: always
    ports:
      - '3000:3000'
    environment:
      ANON_KEY: your-anon-key
      SERVICE_ROLE_KEY: your-service-role-key
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres

  supabase-auth:
    image: supabase/gotrue:v2.26.0
    restart: always
    ports:
      - '9999:9999'
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_JWT_SECRET: your-jwt-secret
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      GOTRUE_SITE_URL: http://localhost:3000

  supabase-realtime:
    image: supabase/realtime:v2.13.0
    restart: always
    ports:
      - '4000:4000'
    environment:
      DB_HOST: postgres
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      PORT: 4000
      SECRET_KEY_BASE: your-secret-key-base

volumes:
  postgres-data: